---

# http://developerblog.redhat.com/2015/11/19/dns-your-openshift-v3-cluster/
- name: dnsmasq local forwarding
  template:
    src: etc/dnsmasq.d/openshift_local_forward.conf.j2
    dest: /etc/dnsmasq.d/openshift_local_forward.conf
    force: no
  notify: restart_dnsmasq