---
- name: Ensure shared sparkles hdf5 dir exists
  file: path="{{ sparkles_dir }}/hdf5" state=directory owner=root mode=0777


- name: Ensure tmp directory exists
  file: path="{{ sparkles_dir }}/tmp" state=directory owner=root mode=0777

- name: Ensure modules directory exists
  file: path="{{ sparkles_dir }}/modules" state=directory owner=root mode=0777

- name: Ensure etc directory exists
  file: path="{{ sparkles_dir }}/etc" state=directory owner=root mode=0777

- name: Copy config.yml.template in etc
  action: template dest="{{ sparkles_dir }}/etc/config.yml.template" src=roles/sparkles/files/config.yml.template owner=root group=root mode=0777
  with_items: "{{ groups['masters'] }}"

- name: Add the default config.yml location for sparkles
  lineinfile: dest=/home/cloud-user/.sparkles_configpath line="{{ sparkles_dir }}/etc/config.yml" state=present create=yes
  when: inventory_hostname_short  == "{{ cluster_name }}-master-1"
